<template>
  <v-app>
    <v-content>
      <v-container fluid fill-height>
        <v-layout align-center justify-center>
          <v-flex xs12 sm8 md8 lg8>
          </div>
          <h1 >Privacy Policy</h1>

        <table >
         <tr>
           <td>Name of the service</td>
           <td>OSCAR</td>
         </tr>
         <tr>
           <td>URLs of the service</td>
           <td>https://ui.oscar.grycap.net/
           </td>
         </tr>
         <tr>
           <td>Description of the service</td>
           <td>OSCAR is an open-source platform to support the Functions as a Service (FaaS) computing model for file-processing applications. It can be automatically deployed on multi-Clouds in order to create highly-parallel event-driven file-processing serverless applications that execute on customized runtime environments provided by Docker containers than run on an elastic Kubernetes cluster. </td>
         </tr>
         <tr>
           <td>Data controller </td>
           <td>Grupo de Grid y Computación de Altas Prestaciones (GRyCAP) de la
           Universitat Politècnica de València (UPV):
           Universitat Politècnica de València
           Camino de Vera s/n
           Edificio 8B, Acc. N, Nivel 1. GRyCAP
           Valencia, Valencia 46022
           Spain
         </br>
           email: products@grycap.upv.es</td>
         </tr>
         <tr>
           <td>Jurisdiction</td>
           <td>ES.Spain (Valencia)</td>
         </tr>
         <tr>
           <td>Personal data
           processed</td>
           <td>None</td>
         </tr>
         <tr>
           <td>Purpose of the
           processing of
           personal data</td>
           <td>None</td>
         </tr>
         <tr>
           <td>Third parties to
           whom personal data
           is disclosed</td>
           <td>None</td>
         </tr>
         <tr>
           <td>How to access,
           rectify and delete
           the personal data
         </td>
           <td>Contact the email: products@grycap.upv.es. To rectify the data
           released by your Home Organisation, contact your Home
           Organisation's IT helpdesk</td>
         </tr>
         <tr>
           <td>Data retention</td>
           <td>No personal data is retained</td>
         </tr>
         <tr>
           <td>Data Protection
           Code of Conduct</td>
           <td>Your personal data, if any, will be protected according to the
             <a target="_blank" href="http://www.geant.net/uri/dataprotection-code-of-conduct/v1">Code of Conduct
           for Service Providers</a>, a common standard for the research and higher
           education sector to protect your privacy</td>
         </tr>
         <tr>
           <td>Cookies</td>
           <td>
              This site uses an internal cookie only to maintain user sessions with the
             server.
             Our website uses Google Analytics, For more information about privacy
             at Google Analytics, please see <a target="_blank" href="https://policies.google.com/privacy">
               Google’s privacy policy</a>. You can
             prevent the collection of the data generated by the cookie and
             transmission to Google by modifying the Cookies Consent.
          </td>
         </tr>
       </table>
          </div>
          </v-flex>
        </v-layout>
      </v-container>
    </v-content>
  </v-app>
</template>

<script>


</script>
<style scoped lang="css">
table, td, th {
  border: 1px solid;
}
td {
  padding-top:10px;
  padding-bottom:10px;
  padding-left:10px;
  padding-right:10px;
}

</style>
