import Vue from 'vue'
import {
  Vuetify,
  VApp,
  VAlert,
  VAvatar,
  VBadge,
  VBreadcrumbs,
  VBtn,
  VBtnToggle,
  VBottomNav,
  VCard,
  VCheckbox,
  VChip,
  VDataTable,
  VDivider,
  VDialog,
  VFooter,
  VForm,
  VGrid,
  VIcon,
  VImg,
  VList,
  VMenu,
  VNavigationDrawer,
  VProgressCircular,
  VProgressLinear,
  VSpeedDial,
  VSnackbar,
  VSubheader,
  VTextField,
  VToolbar,
  VTooltip,
  transitions
} from 'vuetify'
import 'vuetify/src/stylus/app.styl'

Vue.use(Vuetify, {
  components: {
    VApp,
    VAlert,
    VAvatar,
    VBadge,
    VBreadcrumbs,
    VBtn,
    VBtnToggle,
    VBottomNav,
    VCard,
    VCheckbox,
    VChip,
    VDataTable,
    VDialog,
    VDivider,
    VFooter,
    VForm,
    VGrid,
    VIcon,
    VImg,
    VList,
    VMenu,
    VNavigationDrawer,
    VProgressCircular,
    VProgressLinear,
    VSpeedDial,
    VSnackbar,
    VSubheader,
    VTextField,
    VToolbar,
    VTooltip,
    transitions
  }
})
